// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: save.proto

package oms_save_dn

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaveClient is the client API for Save service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaveClient interface {
	SaveNaming(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error)
}

type saveClient struct {
	cc grpc.ClientConnInterface
}

func NewSaveClient(cc grpc.ClientConnInterface) SaveClient {
	return &saveClient{cc}
}

func (c *saveClient) SaveNaming(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, "/oms_save_dn.Save/SaveNaming", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaveServer is the server API for Save service.
// All implementations must embed UnimplementedSaveServer
// for forward compatibility
type SaveServer interface {
	SaveNaming(context.Context, *SaveRequest) (*SaveReply, error)
	mustEmbedUnimplementedSaveServer()
}

// UnimplementedSaveServer must be embedded to have forward compatible implementations.
type UnimplementedSaveServer struct {
}

func (UnimplementedSaveServer) SaveNaming(context.Context, *SaveRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveNaming not implemented")
}
func (UnimplementedSaveServer) mustEmbedUnimplementedSaveServer() {}

// UnsafeSaveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaveServer will
// result in compilation errors.
type UnsafeSaveServer interface {
	mustEmbedUnimplementedSaveServer()
}

func RegisterSaveServer(s grpc.ServiceRegistrar, srv SaveServer) {
	s.RegisterService(&Save_ServiceDesc, srv)
}

func _Save_SaveNaming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveServer).SaveNaming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms_save_dn.Save/SaveNaming",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveServer).SaveNaming(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Save_ServiceDesc is the grpc.ServiceDesc for Save service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Save_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oms_save_dn.Save",
	HandlerType: (*SaveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveNaming",
			Handler:    _Save_SaveNaming_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "save.proto",
}
