// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: save.proto

package oms_save_dn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Clientes envian request a servidor central para procesar su informacion
// Pensar en terminos informaticos mas que linguisticos
// No es que los clientes pidan la severidad, piden procesar la severidad.
type SaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname string `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{0}
}

func (x *SaveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type SaveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SaveReply) Reset() {
	*x = SaveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReply) ProtoMessage() {}

func (x *SaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveReply.ProtoReflect.Descriptor instead.
func (*SaveReply) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{1}
}

func (x *SaveReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_save_proto protoreflect.FileDescriptor

var file_save_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f, 0x6d,
	0x73, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x64, 0x6e, 0x22, 0x4b, 0x0a, 0x0b, 0x53, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x48, 0x0a,
	0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x4e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x6f, 0x6d, 0x73, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x64,
	0x6e, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x6f, 0x6d, 0x73, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x64, 0x6e, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x69, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x75, 0x69,
	0x7a, 0x41, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6c, 0x61, 0x62, 0x32, 0x2f, 0x69, 0x6e,
	0x2f, 0x6f, 0x6d, 0x73, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x64, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_save_proto_rawDescOnce sync.Once
	file_save_proto_rawDescData = file_save_proto_rawDesc
)

func file_save_proto_rawDescGZIP() []byte {
	file_save_proto_rawDescOnce.Do(func() {
		file_save_proto_rawDescData = protoimpl.X.CompressGZIP(file_save_proto_rawDescData)
	})
	return file_save_proto_rawDescData
}

var file_save_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_save_proto_goTypes = []interface{}{
	(*SaveRequest)(nil), // 0: oms_save_dn.SaveRequest
	(*SaveReply)(nil),   // 1: oms_save_dn.SaveReply
}
var file_save_proto_depIdxs = []int32{
	0, // 0: oms_save_dn.Save.SaveNaming:input_type -> oms_save_dn.SaveRequest
	1, // 1: oms_save_dn.Save.SaveNaming:output_type -> oms_save_dn.SaveReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_save_proto_init() }
func file_save_proto_init() {
	if File_save_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_save_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_save_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_save_proto_goTypes,
		DependencyIndexes: file_save_proto_depIdxs,
		MessageInfos:      file_save_proto_msgTypes,
	}.Build()
	File_save_proto = out.File
	file_save_proto_rawDesc = nil
	file_save_proto_goTypes = nil
	file_save_proto_depIdxs = nil
}
